---
name: FlashCore
version: 1.0.2
main: DavidFlash\LobbyCore\Main
api: 3.14.0

commands:
  lobby:
     description: Teleports you to the main hub
  hub:
     description: Teleports you to the main hub
  flashcore:
     description: FlashCore Plugin Help
  fly:
     description: Enables Fly
  nofly:
     description: Disables Fly
...
